### ISSUE TITLE
Saswell已经将自己的API平台从scinan搬移至api.saswell.com.cn

### ISSUE THREAD

**Issue by xia0linz1** [Yonsm/ZhiSaswell#10]
经过和Saswell中国400电话确认，Saswell中国已经于2023年3月底将自己的智能服务从scinan转移至了api.saswell.com.cn。
目前官方APP都已经完成了更新和平台切换，平台切换后账号需要重新注册，大多数旧设备依然支持在新平台使用。
官方声称api.saswell.com.cn将会比scinan更稳定，所以建议项目也同步更新。

PS：我也没找到api.saswell.com.cn的文档，但是看在能兼容旧设备的情况下，应该不会有变化，只能靠抓包大法来猜了。

**Comment by joelliang** [comment]
转战这里吧：https://github.com/Skarbo/hass-scinan-thermostat
这里支持新的 API，我刚提交 PR 支持了水地暖面板，已经 merge 了。
